<h1><?php echo $this->translate('page.about') ?></h1>
<p>
    Depuis 1993 nous sommes spécialisés en vente par correspondance de produits de collection BD et Para-BD. Vous trouverez sur ce site les derniers albums en édition originale, les albums anciens en édition originale, les statuettes ainsi que tout ce qui tourne autour de l’univers de la bande dessinée.
</p>
<p>
    Nous sommes spécialisés dans l'état neuf, néanmoins pour que vous puissiez vous faire une idée très précise de la qualité des albums proposés, nous avons mis au point un système de notation des coiffes et des coins. Tous les nouveaux albums sont strictement triés chez nos fournisseurs. Les albums anciens de collections sont livrés protégés par une pochette plastique ou un CAPITALBUM.
</p>
</p>
<h3>
Comment utiliser ce site ?
</h3>
<p>
Dans l'espace "nouveautés" vous trouverez, les dernières trouvailles de produits BD et para-BD récents et anciens. C’est le meilleur moyen pour vous tenir au courant des derniers arrivages.
</p>
<p>
Vous pouvez accéder directement aux rubriques qui vous intéressent en cliquant sur un type de produit (par exemple: Statuette) puis en sélectionnant un auteur (Uderzo) ou une série (Astérix). Le site fait alors le tri et affiche tous les produits référencés.
</p>
<p>
Vous pouvez aussi faire une recherche par "mot clé", vous afficherez alors tous les produits référencés sur le site. Par exemple si vous tapez "buchet" vous obtiendrez tous les articles (Albums, cartes postales, affiches, statuettes, originaux, exlibris etc...) de Buchet.
</p>
<h3>
Disponibilité des produits ?
</h3>
<p>
La rareté de certain produit que nous vendons, ne nous permet pas de contenter tout le monde en même temps. Alors si d'aventure un produit n'était plus disponible au moment où vous passez votre commande, ne nous en tenez pas rigueur, nous ferons le maximum pour vous en retrouver un autre. La fiche des articles peut indiquer une date prévue des produits à paraître.
</p>
<h3>
Comment faire pour commander ?
</h3>
<p>
Sélectionnez les articles qui vous intéressent sur la page, en cochant la case à côté du prix, puis cliquer sur un panier. Votre panier affiche le nombre d’articles sélectionnés. Vous pouvez le consulter en cliquant en bas de page dans « voir le panier ». Pour modifier ou valider votre commande, affichez le panier et suivez les indications.
</p>
<h3>
Comment sera expédiée ma commande ?
</h3>
<p>
Nous sommes de vrais spécialistes de la Vente à Distance et nous prêtons une attention toute particulière à l'emballage de nos colis pour que votre commande vous parvienne en parfait état. Votre commande est envoyée par colissimo suivi.
</p>
<p>
Nous avons des milliers de clients satisfaits. Notre objectif : vous satisfaire.....et vous compter parmi nos clients heureux !!! Valérie et son équipe vous souhaite une bonne visite.